import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { supabase } from '@/integrations/supabase/client';

export type LanguageCode = 'en' | 'pt' | 'fr' | 'zh' | 'it' | 'es' | 'ar';

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.analyzer': 'AI Analyzer',
    'nav.academy': 'Academy',
    'nav.team': 'My Power Team',
    'nav.settings': 'Settings',
    'nav.properties': 'Properties',
    'nav.logout': 'Sign Out',
    
    // Dashboard
    'dashboard.title': 'Investment Dashboard',
    'dashboard.netWorth': 'Net Worth',
    'dashboard.totalProperties': 'Total Properties',
    'dashboard.monthlyIncome': 'Monthly Income',
    'dashboard.cashOnCash': 'Cash on Cash',
    'dashboard.welcome': 'Welcome back',
    'dashboard.recentActivity': 'Recent Activity',
    
    // Academy
    'academy.title': 'PropWealth Academy',
    'academy.subtitle': 'Master the art of real estate investing',
    'academy.progress': 'Your Progress',
    'academy.markComplete': 'Mark as Complete',
    'academy.completed': 'Completed',
    'academy.continue': 'Continue Learning',
    'academy.module': 'Module',
    'academy.lessons': 'lessons',
    
    // Modules
    'module.mindset.title': 'The Mindset',
    'module.mindset.desc': 'Build the foundation for wealth creation',
    'module.math.title': 'The Math',
    'module.math.desc': 'Master real estate financial analysis',
    'module.ai.title': 'Using the AI',
    'module.ai.desc': 'Leverage AI for smarter investments',
    'module.taxes.title': 'Global Taxes',
    'module.taxes.desc': 'Optimize your international tax strategy',
    'module.team.title': 'Team Building',
    'module.team.desc': 'Assemble your power team',
    
    // Lessons
    'lesson.mindset1': 'From $30k to $1M',
    'lesson.mindset2': 'Forced Appreciation vs Market Speculation',
    'lesson.math1': 'Understanding Cap Rate',
    'lesson.math2': 'NOI Mastery',
    'lesson.math3': 'Cash-on-Cash Return',
    'lesson.ai1': 'Using the Analyzer Tool',
    'lesson.ai2': 'AI-Powered Deal Finding',
    'lesson.taxes1': 'Investing in Dubai (0% Tax)',
    'lesson.taxes2': 'USA 1031 Exchange',
    'lesson.taxes3': 'European Tax Strategies',
    'lesson.team1': 'The Power Team Framework',
    'lesson.team2': 'Finding Your Shark Agent',
    
    // Team
    'team.title': 'My Power Team',
    'team.subtitle': 'Build your real estate dream team',
    'team.addMember': 'Add Member',
    'team.createMember': 'Create Team Member',
    'team.createMemberDesc': 'Create an account for your team member with instant access credentials.',
    'team.inviteSent': 'Invitation sent!',
    'team.name': 'Name',
    'team.email': 'Email',
    'team.password': 'Password',
    'team.passwordHint': 'Click the key icon to generate a secure password',
    'team.role': 'Role',
    'team.noMembers': 'No team members yet',
    'team.inviteFirst': 'Invite your first team member to get started',
    'team.memberCreated': 'Member Created!',
    'team.memberCreatedDesc': 'Team member account has been created successfully.',
    'team.memberCreatedTitle': 'Member Account Created',
    'team.saveCredentialsWarning': 'Save these credentials now. The password cannot be recovered later.',
    'team.loginUrl': 'Login URL',
    'team.copyAllCredentials': 'Copy All Credentials',
    'team.allCredentialsCopied': 'All credentials copied to clipboard',
    'team.sendCredentialsNote': 'Send these credentials to your team member so they can access the platform.',
    'team.createAndGetCredentials': 'Create & Get Credentials',
    'team.accessCredentials': 'Access Credentials',
    'team.publishAppNote': 'Publish your app first for team members to access this URL.',
    
    // Common
    'common.copied': 'Copied!',
    'common.copiedToClipboard': 'copied to clipboard',
    
    // Roles
    'role.owner': 'Owner',
    'role.admin': 'Admin',
    'role.shark_agent': 'The Shark Agent',
    'role.contractor': 'Contractor',
    'role.lender': 'Lender',
    'role.attorney': 'Attorney',
    'role.inspector': 'Inspector',
    'role.member': 'Member',
    
    // Auth
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.fullName': 'Full Name',
    'auth.createAccount': 'Create Account',
    'auth.haveAccount': 'Already have an account?',
    'auth.noAccount': "Don't have an account?",
    'auth.welcomeToTeam': 'Welcome to the Team',
    'auth.setSecurePassword': 'Please set a secure password to continue',
    'auth.newPassword': 'New Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.weak': 'Weak',
    'auth.medium': 'Medium',
    'auth.strong': 'Strong',
    'auth.passwordsMatch': 'Passwords match',
    'auth.passwordsDoNotMatch': 'Passwords do not match',
    'auth.passwordTooShort': 'Password must be at least 8 characters',
    'auth.passwordUpdated': 'Password updated successfully',
    'auth.passwordUpdateFailed': 'Failed to update password',
    'auth.setPasswordAndContinue': 'Set Password & Continue',
    'auth.securityNote': 'Your password is encrypted and never stored in plain text',
    'auth.accessDenied': 'Access Denied',
    'auth.noPermission': 'You do not have permission to access this page. Contact your team administrator.',
    'auth.currentRole': 'Your current role',
    'auth.restrictedArea': 'Restricted Area',
    'auth.insufficientPermissions': 'Your role does not have access to this section.',
    
    // Properties
    'properties.title': 'Properties',
    'properties.subtitle': 'Manage your real estate portfolio',
    'properties.addProperty': 'Add Property',
    'properties.noProperties': 'No properties yet',
    'properties.addFirst': 'Add your first property to get started',
    'properties.price': 'Price',
    'properties.rent': 'Rent',
    'properties.equity': 'equity',
    'properties.addressHidden': 'Address (restricted)',
    'properties.financialDataRestricted': 'Financial data restricted for your role',
    'properties.status.new': 'New',
    'properties.status.analyzing': 'Analyzing',
    'properties.status.negotiating': 'Negotiating',
    'properties.status.acquired': 'Acquired',
    'properties.status.rejected': 'Rejected',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.loading': 'Loading...',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.language': 'Language',
  },
  pt: {
    'nav.dashboard': 'Painel',
    'nav.analyzer': 'Analisador IA',
    'nav.academy': 'Academia',
    'nav.team': 'Minha Equipe',
    'nav.settings': 'Configurações',
    'nav.properties': 'Propriedades',
    'nav.logout': 'Sair',
    'dashboard.title': 'Painel de Investimentos',
    'dashboard.netWorth': 'Patrimônio Líquido',
    'dashboard.totalProperties': 'Total de Propriedades',
    'dashboard.monthlyIncome': 'Renda Mensal',
    'dashboard.cashOnCash': 'Retorno Cash-on-Cash',
    'dashboard.welcome': 'Bem-vindo de volta',
    'dashboard.recentActivity': 'Atividade Recente',
    'academy.title': 'Academia PropWealth',
    'academy.subtitle': 'Domine a arte do investimento imobiliário',
    'academy.progress': 'Seu Progresso',
    'academy.markComplete': 'Marcar como Concluído',
    'academy.completed': 'Concluído',
    'academy.continue': 'Continuar Aprendendo',
    'academy.module': 'Módulo',
    'academy.lessons': 'lições',
    'module.mindset.title': 'A Mentalidade',
    'module.mindset.desc': 'Construa a base para a criação de riqueza',
    'module.math.title': 'A Matemática',
    'module.math.desc': 'Domine a análise financeira imobiliária',
    'module.ai.title': 'Usando a IA',
    'module.ai.desc': 'Aproveite a IA para investimentos mais inteligentes',
    'module.taxes.title': 'Impostos Globais',
    'module.taxes.desc': 'Otimize sua estratégia fiscal internacional',
    'module.team.title': 'Construção de Equipe',
    'module.team.desc': 'Monte sua equipe poderosa',
    'team.title': 'Minha Equipe Poderosa',
    'team.subtitle': 'Construa sua equipe dos sonhos imobiliários',
    'team.addMember': 'Adicionar Membro',
    'team.createMember': 'Criar Membro da Equipe',
    'team.createMemberDesc': 'Crie uma conta para o membro da sua equipe com credenciais de acesso instantâneo.',
    'team.inviteSent': 'Convite enviado!',
    'team.name': 'Nome',
    'team.email': 'E-mail',
    'team.password': 'Senha',
    'team.passwordHint': 'Clique no ícone da chave para gerar uma senha segura',
    'team.role': 'Função',
    'team.noMembers': 'Nenhum membro da equipe ainda',
    'team.inviteFirst': 'Convide seu primeiro membro para começar',
    'team.memberCreated': 'Membro Criado!',
    'team.memberCreatedDesc': 'A conta do membro foi criada com sucesso.',
    'team.memberCreatedTitle': 'Conta do Membro Criada',
    'team.saveCredentialsWarning': 'Salve estas credenciais agora. A senha não pode ser recuperada depois.',
    'team.loginUrl': 'URL de Login',
    'team.copyAllCredentials': 'Copiar Todas as Credenciais',
    'team.allCredentialsCopied': 'Todas as credenciais copiadas',
    'team.sendCredentialsNote': 'Envie estas credenciais para o membro da sua equipe para que ele possa acessar a plataforma.',
    'team.createAndGetCredentials': 'Criar e Obter Credenciais',
    'team.accessCredentials': 'Credenciais de Acesso',
    'team.publishAppNote': 'Publique a sua app primeiro para os membros do team acederem a esta URL.',
    'common.copied': 'Copiado!',
    'common.copiedToClipboard': 'copiado para a área de transferência',
    'role.owner': 'Proprietário',
    'role.admin': 'Administrador',
    'role.shark_agent': 'O Agente Tubarão',
    'role.contractor': 'Empreiteiro',
    'role.lender': 'Credor',
    'role.attorney': 'Advogado',
    'role.inspector': 'Inspetor',
    'role.member': 'Membro',
    'auth.signIn': 'Entrar',
    'auth.signUp': 'Cadastrar',
    'auth.email': 'E-mail',
    'auth.password': 'Senha',
    'auth.fullName': 'Nome Completo',
    'auth.createAccount': 'Criar Conta',
    'auth.haveAccount': 'Já tem uma conta?',
    'auth.noAccount': 'Não tem uma conta?',
    'auth.welcomeToTeam': 'Bem-vindo à Equipe',
    'auth.setSecurePassword': 'Por favor, defina uma senha segura para continuar',
    'auth.newPassword': 'Nova Senha',
    'auth.confirmPassword': 'Confirmar Senha',
    'auth.weak': 'Fraca',
    'auth.medium': 'Média',
    'auth.strong': 'Forte',
    'auth.passwordsMatch': 'As senhas coincidem',
    'auth.passwordsDoNotMatch': 'As senhas não coincidem',
    'auth.passwordTooShort': 'A senha deve ter pelo menos 8 caracteres',
    'auth.passwordUpdated': 'Senha atualizada com sucesso',
    'auth.passwordUpdateFailed': 'Falha ao atualizar senha',
    'auth.setPasswordAndContinue': 'Definir Senha e Continuar',
    'auth.securityNote': 'Sua senha é criptografada e nunca armazenada em texto simples',
    'auth.accessDenied': 'Acesso Negado',
    'auth.noPermission': 'Você não tem permissão para acessar esta página. Contate o administrador da equipe.',
    'auth.currentRole': 'Sua função atual',
    'auth.restrictedArea': 'Área Restrita',
    'auth.insufficientPermissions': 'Sua função não tem acesso a esta seção.',
    'properties.title': 'Propriedades',
    'properties.subtitle': 'Gerencie seu portfólio imobiliário',
    'properties.addProperty': 'Adicionar Propriedade',
    'properties.noProperties': 'Nenhuma propriedade ainda',
    'properties.addFirst': 'Adicione sua primeira propriedade para começar',
    'properties.price': 'Preço',
    'properties.rent': 'Aluguel',
    'properties.equity': 'patrimônio',
    'properties.addressHidden': 'Endereço (restrito)',
    'properties.financialDataRestricted': 'Dados financeiros restritos para sua função',
    'properties.status.new': 'Novo',
    'properties.status.analyzing': 'Analisando',
    'properties.status.negotiating': 'Negociando',
    'properties.status.acquired': 'Adquirido',
    'properties.status.rejected': 'Rejeitado',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.loading': 'Carregando...',
    'common.success': 'Sucesso',
    'common.error': 'Erro',
    'common.language': 'Idioma',
  },
  fr: {
    'nav.dashboard': 'Tableau de bord',
    'nav.analyzer': 'Analyseur IA',
    'nav.academy': 'Académie',
    'nav.team': 'Mon Équipe',
    'nav.settings': 'Paramètres',
    'nav.properties': 'Propriétés',
    'nav.logout': 'Déconnexion',
    'dashboard.title': 'Tableau de bord',
    'dashboard.netWorth': 'Valeur Nette',
    'dashboard.totalProperties': 'Total des Propriétés',
    'dashboard.monthlyIncome': 'Revenu Mensuel',
    'dashboard.cashOnCash': 'Rendement Cash-on-Cash',
    'dashboard.welcome': 'Bienvenue',
    'dashboard.recentActivity': 'Activité Récente',
    'academy.title': 'Académie PropWealth',
    'academy.subtitle': "Maîtrisez l'art de l'investissement immobilier",
    'academy.progress': 'Votre Progression',
    'academy.markComplete': 'Marquer comme terminé',
    'academy.completed': 'Terminé',
    'academy.continue': 'Continuer à apprendre',
    'academy.module': 'Module',
    'academy.lessons': 'leçons',
    'module.mindset.title': "L'État d'Esprit",
    'module.mindset.desc': 'Construisez les bases de la création de richesse',
    'module.math.title': 'Les Mathématiques',
    'module.math.desc': "Maîtrisez l'analyse financière immobilière",
    'module.ai.title': "Utiliser l'IA",
    'module.ai.desc': "Exploitez l'IA pour des investissements plus intelligents",
    'module.taxes.title': 'Fiscalité Mondiale',
    'module.taxes.desc': 'Optimisez votre stratégie fiscale internationale',
    'module.team.title': "Construction d'Équipe",
    'module.team.desc': 'Assemblez votre équipe de choc',
    'team.title': 'Mon Équipe de Choc',
    'team.subtitle': 'Construisez votre équipe immobilière de rêve',
    'team.addMember': 'Ajouter un Membre',
    'team.inviteSent': 'Invitation envoyée!',
    'team.name': 'Nom',
    'team.email': 'E-mail',
    'team.role': 'Rôle',
    'team.noMembers': "Pas encore de membres d'équipe",
    'team.inviteFirst': 'Invitez votre premier membre pour commencer',
    'role.owner': 'Propriétaire',
    'role.admin': 'Administrateur',
    'role.shark_agent': 'Agent Requin',
    'role.contractor': 'Entrepreneur',
    'role.lender': 'Prêteur',
    'role.attorney': 'Avocat',
    'role.inspector': 'Inspecteur',
    'role.member': 'Membre',
    'auth.signIn': 'Se Connecter',
    'auth.signUp': "S'inscrire",
    'auth.email': 'E-mail',
    'auth.password': 'Mot de passe',
    'auth.fullName': 'Nom Complet',
    'auth.createAccount': 'Créer un Compte',
    'auth.haveAccount': 'Vous avez déjà un compte?',
    'auth.noAccount': "Vous n'avez pas de compte?",
    'common.save': 'Sauvegarder',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.loading': 'Chargement...',
    'common.success': 'Succès',
    'common.error': 'Erreur',
    'common.language': 'Langue',
  },
  zh: {
    'nav.dashboard': '仪表板',
    'nav.analyzer': 'AI分析器',
    'nav.academy': '学院',
    'nav.team': '我的团队',
    'nav.settings': '设置',
    'nav.properties': '房产',
    'nav.logout': '退出登录',
    'dashboard.title': '投资仪表板',
    'dashboard.netWorth': '净资产',
    'dashboard.totalProperties': '房产总数',
    'dashboard.monthlyIncome': '月收入',
    'dashboard.cashOnCash': '现金回报率',
    'dashboard.welcome': '欢迎回来',
    'dashboard.recentActivity': '最近活动',
    'academy.title': 'PropWealth学院',
    'academy.subtitle': '掌握房地产投资的艺术',
    'academy.progress': '您的进度',
    'academy.markComplete': '标记完成',
    'academy.completed': '已完成',
    'academy.continue': '继续学习',
    'academy.module': '模块',
    'academy.lessons': '课程',
    'module.mindset.title': '心态',
    'module.mindset.desc': '建立财富创造的基础',
    'module.math.title': '数学',
    'module.math.desc': '掌握房地产财务分析',
    'module.ai.title': '使用AI',
    'module.ai.desc': '利用AI进行更明智的投资',
    'module.taxes.title': '全球税务',
    'module.taxes.desc': '优化您的国际税务策略',
    'module.team.title': '团队建设',
    'module.team.desc': '组建您的强大团队',
    'team.title': '我的强大团队',
    'team.subtitle': '建立您的房地产梦之队',
    'team.addMember': '添加成员',
    'team.inviteSent': '邀请已发送!',
    'team.name': '姓名',
    'team.email': '电子邮件',
    'team.role': '角色',
    'team.noMembers': '还没有团队成员',
    'team.inviteFirst': '邀请您的第一个团队成员开始',
    'role.owner': '所有者',
    'role.admin': '管理员',
    'role.shark_agent': '鲨鱼经纪人',
    'role.contractor': '承包商',
    'role.lender': '贷方',
    'role.attorney': '律师',
    'role.inspector': '检查员',
    'role.member': '成员',
    'auth.signIn': '登录',
    'auth.signUp': '注册',
    'auth.email': '电子邮件',
    'auth.password': '密码',
    'auth.fullName': '全名',
    'auth.createAccount': '创建账户',
    'auth.haveAccount': '已有账户?',
    'auth.noAccount': '没有账户?',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.loading': '加载中...',
    'common.success': '成功',
    'common.error': '错误',
    'common.language': '语言',
  },
  it: {
    'nav.dashboard': 'Dashboard',
    'nav.analyzer': 'Analizzatore IA',
    'nav.academy': 'Accademia',
    'nav.team': 'Il Mio Team',
    'nav.settings': 'Impostazioni',
    'nav.properties': 'Proprietà',
    'nav.logout': 'Esci',
    'dashboard.title': 'Dashboard Investimenti',
    'dashboard.netWorth': 'Patrimonio Netto',
    'dashboard.totalProperties': 'Totale Proprietà',
    'dashboard.monthlyIncome': 'Reddito Mensile',
    'dashboard.cashOnCash': 'Rendimento Cash-on-Cash',
    'dashboard.welcome': 'Bentornato',
    'dashboard.recentActivity': 'Attività Recente',
    'academy.title': 'Accademia PropWealth',
    'academy.subtitle': "Padroneggia l'arte degli investimenti immobiliari",
    'academy.progress': 'I Tuoi Progressi',
    'academy.markComplete': 'Segna come completato',
    'academy.completed': 'Completato',
    'academy.continue': 'Continua ad apprendere',
    'academy.module': 'Modulo',
    'academy.lessons': 'lezioni',
    'module.mindset.title': 'La Mentalità',
    'module.mindset.desc': 'Costruisci le basi per la creazione di ricchezza',
    'module.math.title': 'La Matematica',
    'module.math.desc': "Padroneggia l'analisi finanziaria immobiliare",
    'module.ai.title': "Usare l'IA",
    'module.ai.desc': "Sfrutta l'IA per investimenti più intelligenti",
    'module.taxes.title': 'Tasse Globali',
    'module.taxes.desc': 'Ottimizza la tua strategia fiscale internazionale',
    'module.team.title': 'Costruzione del Team',
    'module.team.desc': 'Assembla il tuo team vincente',
    'team.title': 'Il Mio Team Vincente',
    'team.subtitle': 'Costruisci il tuo team immobiliare dei sogni',
    'team.addMember': 'Aggiungi Membro',
    'team.inviteSent': 'Invito inviato!',
    'team.name': 'Nome',
    'team.email': 'Email',
    'team.role': 'Ruolo',
    'team.noMembers': 'Nessun membro del team ancora',
    'team.inviteFirst': 'Invita il tuo primo membro per iniziare',
    'role.owner': 'Proprietario',
    'role.admin': 'Amministratore',
    'role.shark_agent': 'Agente Squalo',
    'role.contractor': 'Appaltatore',
    'role.lender': 'Prestatore',
    'role.attorney': 'Avvocato',
    'role.inspector': 'Ispettore',
    'role.member': 'Membro',
    'auth.signIn': 'Accedi',
    'auth.signUp': 'Registrati',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.fullName': 'Nome Completo',
    'auth.createAccount': 'Crea Account',
    'auth.haveAccount': 'Hai già un account?',
    'auth.noAccount': 'Non hai un account?',
    'common.save': 'Salva',
    'common.cancel': 'Annulla',
    'common.delete': 'Elimina',
    'common.edit': 'Modifica',
    'common.loading': 'Caricamento...',
    'common.success': 'Successo',
    'common.error': 'Errore',
    'common.language': 'Lingua',
  },
  es: {
    'nav.dashboard': 'Panel',
    'nav.analyzer': 'Analizador IA',
    'nav.academy': 'Academia',
    'nav.team': 'Mi Equipo',
    'nav.settings': 'Configuración',
    'nav.properties': 'Propiedades',
    'nav.logout': 'Cerrar Sesión',
    'dashboard.title': 'Panel de Inversiones',
    'dashboard.netWorth': 'Patrimonio Neto',
    'dashboard.totalProperties': 'Total de Propiedades',
    'dashboard.monthlyIncome': 'Ingreso Mensual',
    'dashboard.cashOnCash': 'Retorno Cash-on-Cash',
    'dashboard.welcome': 'Bienvenido de nuevo',
    'dashboard.recentActivity': 'Actividad Reciente',
    'academy.title': 'Academia PropWealth',
    'academy.subtitle': 'Domina el arte de la inversión inmobiliaria',
    'academy.progress': 'Tu Progreso',
    'academy.markComplete': 'Marcar como completado',
    'academy.completed': 'Completado',
    'academy.continue': 'Continuar aprendiendo',
    'academy.module': 'Módulo',
    'academy.lessons': 'lecciones',
    'module.mindset.title': 'La Mentalidad',
    'module.mindset.desc': 'Construye la base para la creación de riqueza',
    'module.math.title': 'Las Matemáticas',
    'module.math.desc': 'Domina el análisis financiero inmobiliario',
    'module.ai.title': 'Usando la IA',
    'module.ai.desc': 'Aprovecha la IA para inversiones más inteligentes',
    'module.taxes.title': 'Impuestos Globales',
    'module.taxes.desc': 'Optimiza tu estrategia fiscal internacional',
    'module.team.title': 'Construcción de Equipo',
    'module.team.desc': 'Ensambla tu equipo poderoso',
    'team.title': 'Mi Equipo Poderoso',
    'team.subtitle': 'Construye tu equipo inmobiliario de ensueño',
    'team.addMember': 'Agregar Miembro',
    'team.inviteSent': '¡Invitación enviada!',
    'team.name': 'Nombre',
    'team.email': 'Correo electrónico',
    'team.role': 'Rol',
    'team.noMembers': 'Aún no hay miembros del equipo',
    'team.inviteFirst': 'Invita a tu primer miembro para comenzar',
    'role.owner': 'Propietario',
    'role.admin': 'Administrador',
    'role.shark_agent': 'Agente Tiburón',
    'role.contractor': 'Contratista',
    'role.lender': 'Prestamista',
    'role.attorney': 'Abogado',
    'role.inspector': 'Inspector',
    'role.member': 'Miembro',
    'auth.signIn': 'Iniciar Sesión',
    'auth.signUp': 'Registrarse',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.fullName': 'Nombre Completo',
    'auth.createAccount': 'Crear Cuenta',
    'auth.haveAccount': '¿Ya tienes una cuenta?',
    'auth.noAccount': '¿No tienes una cuenta?',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.loading': 'Cargando...',
    'common.success': 'Éxito',
    'common.error': 'Error',
    'common.language': 'Idioma',
  },
  ar: {
    'nav.dashboard': 'لوحة التحكم',
    'nav.analyzer': 'محلل الذكاء الاصطناعي',
    'nav.academy': 'الأكاديمية',
    'nav.team': 'فريقي',
    'nav.settings': 'الإعدادات',
    'nav.properties': 'العقارات',
    'nav.logout': 'تسجيل الخروج',
    'dashboard.title': 'لوحة تحكم الاستثمار',
    'dashboard.netWorth': 'صافي الثروة',
    'dashboard.totalProperties': 'إجمالي العقارات',
    'dashboard.monthlyIncome': 'الدخل الشهري',
    'dashboard.cashOnCash': 'العائد النقدي',
    'dashboard.welcome': 'مرحباً بعودتك',
    'dashboard.recentActivity': 'النشاط الأخير',
    'academy.title': 'أكاديمية PropWealth',
    'academy.subtitle': 'أتقن فن الاستثمار العقاري',
    'academy.progress': 'تقدمك',
    'academy.markComplete': 'وضع علامة مكتمل',
    'academy.completed': 'مكتمل',
    'academy.continue': 'متابعة التعلم',
    'academy.module': 'وحدة',
    'academy.lessons': 'دروس',
    'module.mindset.title': 'العقلية',
    'module.mindset.desc': 'بناء أساس خلق الثروة',
    'module.math.title': 'الرياضيات',
    'module.math.desc': 'إتقان التحليل المالي العقاري',
    'module.ai.title': 'استخدام الذكاء الاصطناعي',
    'module.ai.desc': 'استفد من الذكاء الاصطناعي لاستثمارات أذكى',
    'module.taxes.title': 'الضرائب العالمية',
    'module.taxes.desc': 'تحسين استراتيجيتك الضريبية الدولية',
    'module.team.title': 'بناء الفريق',
    'module.team.desc': 'اجمع فريقك القوي',
    'team.title': 'فريقي القوي',
    'team.subtitle': 'ابنِ فريق أحلامك العقاري',
    'team.addMember': 'إضافة عضو',
    'team.inviteSent': 'تم إرسال الدعوة!',
    'team.name': 'الاسم',
    'team.email': 'البريد الإلكتروني',
    'team.role': 'الدور',
    'team.noMembers': 'لا يوجد أعضاء في الفريق بعد',
    'team.inviteFirst': 'ادعُ أول عضو في فريقك للبدء',
    'role.owner': 'المالك',
    'role.admin': 'المسؤول',
    'role.shark_agent': 'وكيل القرش',
    'role.contractor': 'المقاول',
    'role.lender': 'المُقرض',
    'role.attorney': 'المحامي',
    'role.inspector': 'المفتش',
    'role.member': 'عضو',
    'auth.signIn': 'تسجيل الدخول',
    'auth.signUp': 'إنشاء حساب',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.fullName': 'الاسم الكامل',
    'auth.createAccount': 'إنشاء حساب',
    'auth.haveAccount': 'لديك حساب بالفعل؟',
    'auth.noAccount': 'ليس لديك حساب؟',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.loading': 'جاري التحميل...',
    'common.success': 'نجاح',
    'common.error': 'خطأ',
    'common.language': 'اللغة',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>('en');

  const isRTL = language === 'ar';

  useEffect(() => {
    // Update document direction
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const setLanguage = async (lang: LanguageCode) => {
    setLanguageState(lang);
    
    // Try to save to profile if user is logged in
    const { data: { user } } = await supabase.auth.getUser();
    if (user) {
      await supabase
        .from('profiles')
        .update({ language_pref: lang })
        .eq('id', user.id);
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
