import React, { useState } from 'react';
import { Download, FileText, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useLanguage } from '@/contexts/LanguageContext';
import { toast } from 'sonner';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

interface ExportPDFButtonProps {
  targetRef: React.RefObject<HTMLDivElement>;
  fileName?: string;
  portfolioData?: {
    totalValue: number;
    totalCashflow: number;
    propertyCount: number;
    averageROI: number;
  };
}

const ExportPDFButton: React.FC<ExportPDFButtonProps> = ({ 
  targetRef, 
  fileName = 'portfolio-analytics',
  portfolioData 
}) => {
  const { t } = useLanguage();
  const [isExporting, setIsExporting] = useState(false);

  const exportToPDF = async () => {
    if (!targetRef.current) {
      toast.error('Unable to export. Please try again.');
      return;
    }

    setIsExporting(true);
    toast.info('Generating PDF report...');

    try {
      const element = targetRef.current;
      
      // Create canvas from the element
      const canvas = await html2canvas(element, {
        scale: 2,
        useCORS: true,
        logging: false,
        backgroundColor: '#0a0e1a',
        windowWidth: element.scrollWidth,
        windowHeight: element.scrollHeight,
      });

      const imgData = canvas.toDataURL('image/png');
      
      // Calculate PDF dimensions
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      });

      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      
      // Add header
      pdf.setFillColor(10, 14, 26); // Dark background
      pdf.rect(0, 0, pdfWidth, 40, 'F');
      
      pdf.setTextColor(16, 185, 129); // Primary green
      pdf.setFontSize(24);
      pdf.text('PropWealth AI', 15, 20);
      
      pdf.setTextColor(148, 163, 184); // Muted text
      pdf.setFontSize(10);
      pdf.text('Portfolio Analytics Report', 15, 30);
      pdf.text(new Date().toLocaleDateString('en-US', { 
        year: 'numeric', 
        month: 'long', 
        day: 'numeric' 
      }), pdfWidth - 15, 30, { align: 'right' });

      // Add summary section if portfolio data available
      if (portfolioData) {
        pdf.setFillColor(15, 23, 42); // Secondary background
        pdf.rect(10, 45, pdfWidth - 20, 30, 'F');
        
        pdf.setTextColor(255, 255, 255);
        pdf.setFontSize(12);
        pdf.text('Portfolio Summary', 15, 55);
        
        pdf.setFontSize(10);
        pdf.setTextColor(148, 163, 184);
        
        const summaryY = 65;
        const colWidth = (pdfWidth - 30) / 4;
        
        // Portfolio Value
        pdf.text('Portfolio Value', 15, summaryY);
        pdf.setTextColor(16, 185, 129);
        pdf.text(`$${portfolioData.totalValue.toLocaleString()}`, 15, summaryY + 5);
        
        // Monthly Cashflow
        pdf.setTextColor(148, 163, 184);
        pdf.text('Monthly Cashflow', 15 + colWidth, summaryY);
        pdf.setTextColor(16, 185, 129);
        pdf.text(`$${portfolioData.totalCashflow.toLocaleString()}`, 15 + colWidth, summaryY + 5);
        
        // Properties
        pdf.setTextColor(148, 163, 184);
        pdf.text('Properties', 15 + colWidth * 2, summaryY);
        pdf.setTextColor(255, 255, 255);
        pdf.text(portfolioData.propertyCount.toString(), 15 + colWidth * 2, summaryY + 5);
        
        // Average ROI
        pdf.setTextColor(148, 163, 184);
        pdf.text('Average ROI', 15 + colWidth * 3, summaryY);
        pdf.setTextColor(16, 185, 129);
        pdf.text(`${portfolioData.averageROI.toFixed(1)}%`, 15 + colWidth * 3, summaryY + 5);
      }

      // Add charts image
      const chartStartY = portfolioData ? 85 : 50;
      const imgWidth = pdfWidth - 20;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      
      // Check if we need multiple pages
      const availableHeight = pdfHeight - chartStartY - 20;
      
      if (imgHeight > availableHeight) {
        // Scale down to fit
        const scaledHeight = availableHeight;
        const scaledWidth = (canvas.width * scaledHeight) / canvas.height;
        pdf.addImage(imgData, 'PNG', 10, chartStartY, scaledWidth, scaledHeight);
      } else {
        pdf.addImage(imgData, 'PNG', 10, chartStartY, imgWidth, imgHeight);
      }

      // Add footer
      pdf.setFontSize(8);
      pdf.setTextColor(100, 116, 139);
      pdf.text(
        'Generated by PropWealth AI - Your Global Real Estate OS',
        pdfWidth / 2,
        pdfHeight - 10,
        { align: 'center' }
      );

      // Save the PDF
      pdf.save(`${fileName}-${new Date().toISOString().split('T')[0]}.pdf`);
      
      toast.success('PDF report downloaded successfully!');
    } catch (error) {
      console.error('Export error:', error);
      toast.error('Failed to generate PDF. Please try again.');
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <Button 
      onClick={exportToPDF}
      disabled={isExporting}
      className="btn-premium gap-2"
    >
      {isExporting ? (
        <>
          <Loader2 className="w-4 h-4 animate-spin" />
          <span className="hidden sm:inline">{t('analytics.generating') || 'Generating...'}</span>
        </>
      ) : (
        <>
          <Download className="w-4 h-4" />
          <span className="hidden sm:inline">{t('analytics.exportPDF') || 'Export PDF'}</span>
        </>
      )}
    </Button>
  );
};

export default ExportPDFButton;
